//stage('Build') {
    //steps {
      //  sh 'mvn clean install'
    //}
//}

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Build started'
            }
        }
    }
}